# ---------- build stage ----------
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app                    
COPY pom.xml .                  
RUN mvn -q dependency:go-offine  
COPY src ./src
RUN mvn -q clean package -DskipTests

# ---------- run stage ----------
FROM openjdk:17.0.1-jdk-slim
WORKDIR /app
COPY --from=build /app/target/nscbackend-0.0.1-SNAPSHOT.jar nscbackend.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","nscbackend.jar"]