# PostgreSQL DB settings
spring.datasource.url=jdbc:postgresql://dpg-da7g85ou01pc739bb3hg-a.oregon-postgres.render.com/nscdb_m97m?sslmode=require
spring.datasource.username=nscdb_m97m_user
spring.datasource.password=B6hkOHo1BJ1QPYejzvRwRFXGvFiq1NjZ

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect