# PostgreSQL DB settings
spring.datasource.url=jdbc:postgresql://dpg-d5ftrv24d50c73ffd7pg-a.oregon-postgres.render.com/nscdb_07au?sslmode=require
spring.datasource.username=nscdb_07au_user
spring.datasource.password=OxxgAmmJG7w2bYhgIhOliuvS4KYd6ImI

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect