# PostgreSQL DB settings
spring.datasource.url=jdbc:postgresql://dpg-d8ffr76rnols73b57c90-a.oregon-postgres.render.com/nscdb_14em?sslmode=require
spring.datasource.username=nscdb_14em_user
spring.datasource.password=iSAgCMn8iWOCP5GctAiJG3ZY0KHH6EpX

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect